### ISSUE TITLE
install help?

### ISSUE THREAD

**Issue by dakota11** [FGM/accounts-drupal#19]
Looks like a great module, if I could only get it to install.

Getting this error in Meteor on startup :

`Settings are missing a accounts-drupal root key. [drupal-configuration] {"isClientSafe":true,"error":"drupal-configuration","reason":"Settings are missing a accounts-drupal root key.","errorType":"Meteor.Error"}`

I installed the meteor Drupal module but I can't find where the key is generated.

Thanks!

note :  Just added the package locally and the tests completed successfully.  But still get the error.

**Comment by dakota11** [comment]
ok works...

I wasn't starting meteor with : 

`meteor --settings settings.json`

**Comment by fgm** [comment]
Good that you found it yourself :-) You can base the settings.json for your project on the example file provided in the package.
